name: Generate Datas
permissions:
  contents: write
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: vitorbarcelos
          gif_out_path: dist/github-snake.gif
          svg_out_path: dist/github-snake.svg
          
      - uses: dailydotdev/action-devcard@2.0.4
        id: dailydev
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
